version: 2
updates:
  - package-ecosystem: npm
    directory: api
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    assignees:
      - lentz
    ignore:
      - dependency-name: '@types/node'
  - package-ecosystem: npm
    directory: client
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    assignees:
      - lentz
    ignore:
      - dependency-name: '@angular*'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    assignees:
      - lentz
