version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
  - lentz
  ignore:
  - dependency-name: "@angular/cli"
    versions:
    - "> 9.1.0"
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - "> 0.901.1"
  - dependency-name: "@types/node"
    versions:
    - "> 10.17.21"
  - dependency-name: "@types/node"
    versions:
    - ">= 11.a, < 12"
  - dependency-name: "@types/node"
    versions:
    - ">= 12.a, < 13"
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
