version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      timezone: America/New_York
    open-pull-requests-limit: 10
    assignees:
      - lentz
    ignore:
      - dependency-name: '@angular*'
      - dependency-name: '@types/node'
