language: node_js
node_js:
  - "8"
install: npm install
before_install:
  - npm i -g npm@6.1.0
  - npm i -g greenkeeper-lockfile@1
script: npm run ci
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
