services:
  api:
    build: ./api
    pull_policy: build
    env_file: ./api/.env
    ports:
      - '9229:9229'
    volumes:
      - './api:/app'
      - 'api_node_modules:/app/node_modules'

  client:
    build: ./client
    pull_policy: build
    ports:
      - '4200:4200'
    volumes:
      - './client:/app'
      - 'client_node_modules:/app/node_modules'

volumes:
  api_node_modules:
  client_node_modules:
