services:
  api:
    build: ./api
    env_file: ./api/.env
    ports:
      - '9229:9229'
    volumes:
      - './api:/app'
      - /app/node_modules

  client:
    build: ./client
    ports:
      - '4200:4200'
    volumes:
      - './client:/app'
      - /app/node_modules
