services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 9229:9229
    env_file: ./api/.env
    environment:
      - BASE_URL=http://localhost:4200
      - DATABASE_NAME=dev
      - PORT=3000
    volumes:
      - ./api:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./client:/app
      - /app/node_modules
