services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - '9229:9229'
    env_file: .env
    volumes:
      - ./api:/app/api
      - ./client/:/app/client
      - /app/node_modules

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./client/:/app/client
      - /app/node_modules
