name: CI

on:
  pull_request:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      ADMIN_EMAIL: test@example.com
      AUTH0_CLIENT_ID: fake-client
      AUTH0_CLIENT_SECRET: fake-secret
      BUDDYDUEL_URL: http://localhost
      MONGODB_URI: 'mongodb://localhost'
      ODDS_API_KEY: fake-key
      PORT: 3000
      SENDGRID_API_KEY: 'SG.TEST_KEY'
      SESSION_SECRET: test
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: '6.0'
      - name: Install Client Deps
        run: npm ci
        working-directory: ./client
      - name: Lint Client
        run: npm run lint
        working-directory: ./client
      - name: Build Client
        run: npm run build:prod
        working-directory: ./client
      - name: Install API Deps
        run: npm ci
        working-directory: ./api
      - name: Lint API
        run: npm run lint
        working-directory: ./api
      - name: Build API
        run: npm run build
        working-directory: ./api
      - name: Test API
        env:
          DATABASE_NAME: 'integration'
        run: npm run test:ci
        working-directory: ./api
      - name: E2E Test
        uses: cypress-io/github-action@v6
        env:
          DATABASE_NAME: 'e2e'
        with:
          start: node ../api/dist/server.js
          working-directory: ./client
