name: Pull Request

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ github.repository }}
          fetch-depth: 0
      - name: Test
        uses: ./.github/workflows/ci.yml
